# Generated by Django 3.1 on 2022-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='complete',
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='workoutSets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='workoutReps',
            field=models.IntegerField(default=0),
        ),
    ]
