# Generated by Django 3.1 on 2022-07-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220724_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutentry',
            old_name='workoutComment',
            new_name='exerciseComment',
        ),
        migrations.RemoveField(
            model_name='workoutentry',
            name='workoutReps',
        ),
        migrations.RemoveField(
            model_name='workoutentry',
            name='workoutSets',
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='exerciseName',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='exerciseReps',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='exerciseSets',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
