# Generated by Django 3.1 on 2022-10-09 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221009_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutentry',
            name='exerciseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='exerciseReps',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='exerciseSets',
            field=models.IntegerField(default='0'),
        ),
    ]
