# Generated by Django 3.1 on 2022-10-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221009_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutentry',
            name='exerciseDate',
            field=models.DateField(auto_now=True),
        ),
    ]
