# Generated by Django 3.1 on 2022-10-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221009_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='exerciseDate',
        ),
    ]
