# Generated by Django 3.1 on 2022-10-09 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_workoutentry_exercisedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutentry',
            name='exerciseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
